### ISSUE TITLE
把「是否需要協助拍攝?」給刪掉

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#10]

**Comment by carlos411** [comment]
@hungmi 
已移除。
url：http://localhost:3000/houses/26/photo
示意圖：
<img width="769" alt="screen shot 2015-11-09 at 12 36 40 am" src="https://cloud.githubusercontent.com/assets/2485529/11021364/fab68ec4-8679-11e5-8a56-91850451f989.png">

@godorzme
