### ISSUE TITLE
發布圖片的標誌還是沒有圖片，另外上傳後的小圖有點太小了、難以檢視

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#105]
左邊是之前的，右邊是新上傳的
不過房源頁面的圖片顯示讚，只是小圖小小的，小圖可以用之前的方式即可　
![image](https://cloud.githubusercontent.com/assets/15365098/11391322/a461fcc8-938c-11e5-8fbf-19f5986634c3.png)

**Comment by hungmi** [comment]
這可能要等carlos調整，因為如果要符合大螢幕的尺寸的話，其實也是小圖(140*120)放大，解析度並不好，那如果我設定在上傳的時候多存一張例如280*240的圖片當作預覽的話，會更多佔amazon的空間

所以比較好的方法應該是調整成
![image](https://cloud.githubusercontent.com/assets/8531846/11413623/f1bc4f66-9425-11e5-8f60-1d53233a2883.png)
