### ISSUE TITLE
設計沒填完無法刊登

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#11]
需要讓他每個流程都起碼友動作(例如友照片刊登了)，才能刊登

**Comment by hungmi** [comment]
@godorzme 可以再說明詳細點嗎
例如分頁面說明

頁面 | 哪些必填
------ | ------
必填資料 | 全部
傢俱及設施 | 可都不填
描述 | 房屋名稱
圖片 | 至少一張圖片

若為整層住家

頁面 | 哪些必填
------ | ------
空間及價格 | 租金、最短租期
預約及開放 | 預約日可不填，正式可出租日必填

若為分租套雅房

頁面 | 哪些必填
------ | ------
房間 | 至少一間

**Comment by godorzme** [comment]
@hungmi 
基礎資訊:房屋類型、歡迎外國人嗎、地址、學校
空間及價格:租金、租期(分租套雅房的話則不用)、格局、所在樓層
描述:房名、關於房屋
傢俱及設施:設施
圖片:至少一張
(分租套雅房下)房間:至少一間，裡面內容除了預約的日期和出租日期全填
