### ISSUE TITLE
地圖再大，並把標題與符號刪去

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#126]
![image](https://cloud.githubusercontent.com/assets/15365098/11458008/256d93f4-96f3-11e5-9930-75e014080751.png)
(標題與符號指的是地址和他左邊的那個)

**Comment by carlos411** [comment]
@hungmi @godorzme 
updated to develop.

縮放等級目前設為16，我看目前有些寫法是共用的，所以更改縮放等級，似乎也會影響到搜尋頁的地圖的樣子。

更新如下：
<img width="911" alt="screen shot 2015-11-30 at 12 40 12 pm" src="https://cloud.githubusercontent.com/assets/2485529/11463644/0094ce40-9760-11e5-8cf2-43f9fe3d70a7.png">
