### ISSUE TITLE
在"我的房屋列表"下的房屋目錄，另做成一個目錄按鈕放在"我的房屋列表"旁

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#17]
並把"我的房屋列表"改成"我的房源"

**Comment by carlos411** [comment]
@godorzme @hungmi 
請問"房屋目錄"指的是？ 以及所放的位置？

指的是下圖"我的房屋列表"的右側，放一個按鈕(文字為"目錄") 這樣嗎？
<img width="709" alt="screen shot 2015-11-11 at 11 13 27 am" src="https://cloud.githubusercontent.com/assets/2485529/11083017/5cee6214-8865-11e5-9ba8-c485d2191988.png">

然後"我的房屋列表"改成"我的房源"。

**Comment by godorzme** [comment]
房源目錄是指點進房源列表的那一頁：https://zuker.herokuapp.com/houses
其他你的敘述沒錯

**Comment by carlos411** [comment]
@godorzme @hungmi 

因為有相依性，此 issue 已直接 merge 至 `feature/#7_wish_list` 這個 branch 。
view： `app/views/users/profile.html.erb`
```
<h1 class="ui dividing header">
    <%= link_to I18n.t('users.my_houses'), houses_path %>
    <%= link_to "目錄", houses_path, :class => "btn btn-primary btn-xs" %>
  </h1>
```

示意圖：
<img width="1214" alt="screen shot 2015-11-11 at 10 26 20 pm" src="https://cloud.githubusercontent.com/assets/2485529/11093127/4f28bff4-88c3-11e5-83ed-85da5f19e47e.png">
