### ISSUE TITLE
上傳的圖片改為橫排顯示，並與貼URL處做標號

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#18]

**Comment by carlos411** [comment]
@godorzme @hungmi 
不好意思請提供url，感謝啊~~

**Comment by godorzme** [comment]
http://zuker.herokuapp.com/houses/1/photo
要登入才能看

**Comment by hungmi** [comment]
已改為每排顯示三張
請參考https://zuker-beta.herokuapp.com/houses/1/photo
@godorzme 如需再修改成橫排可assign給 @carlos411
