### ISSUE TITLE
封面照的勾選

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#19]

**Comment by godorzme** [comment]
目前在分租套雅房頁面中上傳照片沒有可以勾選封面照的地方?

**Comment by hungmi** [comment]
剛弄好，在每張圖片的最下方有一個Set Cover
https://zuker-beta.herokuapp.com/houses/1/photo
再麻煩 @carlos411 優化

**Comment by carlos411** [comment]
@hungmi @godorzme 
updated to develop.

示意圖：
<img width="810" alt="screen shot 2015-11-18 at 4 37 35 pm" src="https://cloud.githubusercontent.com/assets/2485529/11236230/e17d8660-8e12-11e5-97ca-6893955b4300.png">

**Comment by godorzme** [comment]
set cover 移到 remove image 右邊
並中文化

**Comment by carlos411** [comment]
@godorzme @hungmi 
updated to develop.

示意圖：
<img width="907" alt="screen shot 2015-11-20 at 11 03 46 am" src="https://cloud.githubusercontent.com/assets/2485529/11291002/b400de0c-8f76-11e5-9af0-c62985e42336.png">

**Comment by godorzme** [comment]
讚!只是希望圖樣有辦法也顯示在網站上@@目前的沒有

**Comment by carlos411** [comment]
@godorzme 
待 @hungmi 整合好後，應該就會在線上看到囉， FED 做的東西通常是還不能上線。
目前會專注在介面上喔。
