### ISSUE TITLE
URL輸入處下面做一個”確認”按鈕統一做確認動作 

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#20]
URL輸入後發限需要按”enter”才會真的有輸入，不方便檢查

**Comment by carlos411** [comment]
@godorzme @hungmi 
請提供url，感謝。

**Comment by godorzme** [comment]
http://zuker.herokuapp.com/houses/4/photo
必須登入
目前是必須上傳照片才能貼上全景的url 但不知道貼上後有沒有被記錄 我後來發現只貼上沒有 必須案enter才有

**Comment by hungmi** [comment]
已改為填上就儲存
請參考https://zuker-beta.herokuapp.com/houses/1/photo
若找不到頁面，請重新登入並刊登房屋
