### ISSUE TITLE
照片需要能做顯示排序 

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#21]
哪個第一哪個第二等等

**Comment by carlos411** [comment]
@hungmi @godorzme 
請提供url，感謝。

**Comment by godorzme** [comment]
http://zuker.herokuapp.com/houses/4/photo
必須登入
這是整層出租的頁面 分租套雅房的也需要

**Comment by carlos411** [comment]
@hungmi 
不好意思，我要測試圖片上傳，但似乎無法傳上去，以下為我的步驟：

step1：進入此頁(https://zuker.herokuapp.com/houses/2/photo)：
<img width="872" alt="screen shot 2015-11-11 at 10 05 22 pm" src="https://cloud.githubusercontent.com/assets/2485529/11092719/5e10bd58-88c0-11e5-8fed-8c9f2a3f8783.png">

step2：選一張圖，大小約300k以下，按下"開始上傳圖片"，出現空白畫面，網址停留在https://zuker.herokuapp.com/houses/2

**Comment by carlos411** [comment]
提供我本機端的畫面：
<img width="1019" alt="screen shot 2015-11-11 at 10 08 53 pm" src="https://cloud.githubusercontent.com/assets/2485529/11092791/e269fa24-88c0-11e5-92e8-c8eccba3a145.png">

**Comment by hungmi** [comment]
那要等我這邊deploy才行

**Comment by hungmi** [comment]
@carlos411 請先使用https://zuker-beta.herokuapp.com/houses/1/photo做測試，此為develop分支

**Comment by carlos411** [comment]
@godorzme 
每一個項目會提供一個輸入框(input text)，僅輸入大於等於1的整數，依此排序。若遇到同整數的，則同整數的隨機排。
請確認需求，感謝啊~~

@hungmi

**Comment by godorzme** [comment]
我的想法是:
1.最簡單是做拉霸，排1至看照片數量
2.能的話用拖曳的方式，讓照片上傳的顯示即為排序，第一個就是第一張、依此類推

**Comment by carlos411** [comment]
@hungmi 
<img width="299" alt="screen shot 2015-11-18 at 7 58 59 pm" src="https://cloud.githubusercontent.com/assets/2485529/11240556/d7f00ef8-8e2e-11e5-949f-2601ff940b99.png">

麻煩放欄位填入數字，可做排序。

**Comment by hungmi** [comment]
@carlos411 再麻煩你改善介面

**Comment by godorzme** [comment]
上面的是要把數字寫在room嗎？
把room換成順序
英文是order

**Comment by hungmi** [comment]
欄位我已經換過了，沒辦法用嗎？

**Comment by godorzme** [comment]
beta板的界面目前是舊版的   還有room在  也沒有任何可以填數字的地方?
麻煩了

**Comment by godorzme** [comment]
@carlos411  @hungmi 
排序在房源頁面的結果不正確，麻煩簡查，請優先處理
(友人已經在見房東了)

**Comment by carlos411** [comment]
@hungmi 
#21 我看已合併到develop，但似乎整合不完全。我目前在新版的 develop branch 介面一樣是舊的。
若feature還沒完成，建議不要合併到 develop。
