### ISSUE TITLE
房東回覆評論下顯示日期即可，房東名稱顯示在照片下，點照片可以連皆至個人頁面

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#24]

**Comment by carlos411** [comment]
@godorzme @hungmi 
請問是否是指這區：
<img width="702" alt="screen shot 2015-11-09 at 10 23 09 pm" src="https://cloud.githubusercontent.com/assets/2485529/11035967/82c8002a-8730-11e5-96f3-81d477093bf1.png">
房東名稱是圖中的 "thiel97" 這個位置嗎？ "House5"這位置的文字是否移除？

**Comment by godorzme** [comment]
是的是這個

**Comment by carlos411** [comment]
@hungmi 
branch： feature/#24_comment
view：app/views/comments/_comment.html.erb
請代入以下連結(點照片可以連皆至個人頁面")
```
<a href="#">
    <%= image_tag(comment.author.try(:image) || "image.png", class: 'ui image tiny circular') %>
  </a>
```
示意圖：
<img width="734" alt="screen shot 2015-11-09 at 10 51 05 pm" src="https://cloud.githubusercontent.com/assets/2485529/11036579/63c73246-8734-11e5-85ad-6f1c20bacd71.png">

有一槓橫線的我之後再來改，那需要調整css才能移除，css相關部份我先不調整，我後續會調整FED的架構。
