### ISSUE TITLE
搜尋bar加租金搜尋範圍  

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#26]

**Comment by carlos411** [comment]
@hungmi 
branch： feature/#26_searchbar
view： `app/views/common/_search_form.html.haml`
有新增這行，請代入正確資料：
```
= f.select :money_eq, House.option_categories('person') << ["不限金額",99999], { selected: p || 99999 }, { class: 'form-control ui search dropdown' }
```

選單部份我覺得可以用例如：
0~9999、10000~20000之類的。

示意圖(最右邊有個不限金額選單)
<img width="1050" alt="screen shot 2015-11-08 at 11 41 25 pm" src="https://cloud.githubusercontent.com/assets/2485529/11021109/b0565d48-8672-11e5-8de7-1175f77e392b.png">


@godorzme

**Comment by godorzme** [comment]
呈現會是選單還是拉霸？偏向用拉霸

**Comment by carlos411** [comment]
目前是下拉選單喔(即拉霸)。

**Comment by godorzme** [comment]
喔喔 我指的是像設計圖那樣的左右範圍拉霸

**Comment by carlos411** [comment]
好的，瞭解喔，我覺得可以先讓功能work、資訊正確。
介面的部份我們後續可以來整個調整，左右拉霸會需要另外花時間。

**Comment by hungmi** [comment]
了解
