### ISSUE TITLE
房源頁面未顯示"開始預約日期"與"起租日期"

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#32]
從這裡設定的東西:https://zuker.herokuapp.com/houses/1/date_status
房源頁面沒有顯示:https://zuker.herokuapp.com/houses/1

可能需要自己登錄防間才會發現

房源頁面中:
整層出租的，顯示在租金下面，多一個項目"出租狀況"
分租套雅房，顯示在表格中的"出租狀況"下

**Comment by carlos411** [comment]
@hungmi @godorzme 
branch： `feature/#32_house_page_reservation_and_start_rent`
view： `app/views/houses/show.html.erb`
```
<div class="margin-bottom">
      <label class="label_rent_status">出租狀況：</label>
      <div>
        開始預約日期：2015-11-11<br>
        起租日期：2015-11-12
      </div>
    </div>
```
示意圖：
<img width="1221" alt="screen shot 2015-11-11 at 11 29 10 pm" src="https://cloud.githubusercontent.com/assets/2485529/11094686/0bfc604c-88cc-11e5-8a0e-552e252ec48c.png">

另外還有一個分租套雅房，可能麻煩 @hungmi 先直接放進表格內可能較快，另外因為是共用同一個檔案，需要加判斷式。

**Comment by hungmi** [comment]
done.
I will push to zuker-beta later.

**Comment by godorzme** [comment]
目前都是顯示＂已出租＂，但我放的房源應該是＂可以預約＂，並旁邊要顯示可入住日期

**Comment by hungmi** [comment]
@carlos411 目前你更改過的房源頁面有
“開始預約日期"與"起租日期”
嗎？

**Comment by godorzme** [comment]
@carlos 分租套雅房的也需要

**Comment by carlos411** [comment]
@hungmi 
branch： `feature/#32_date_position`
我本機url： `http://localhost:3000/houses/2`

示意圖：
第一張圖：
<img width="861" alt="screen shot 2015-11-22 at 4 38 11 pm" src="https://cloud.githubusercontent.com/assets/2485529/11322799/ad3cdcca-9137-11e5-97ce-834980bf62e3.png">

第二張圖：
<img width="795" alt="screen shot 2015-11-22 at 4 38 14 pm" src="https://cloud.githubusercontent.com/assets/2485529/11322800/b46e72ce-9137-11e5-9e67-3e9048a4efd1.png">

**Comment by godorzme** [comment]
@hungmi 先用舊版的沒有關係  這個頁面我們新奇三討論過後再用
只要舊版的能跟目前你已經在發佈房源那有做的，可以顯示可入住日期即可

**Comment by godorzme** [comment]
目前beta板的房源頁面都是新的這個  現在也來不及細調了   先用舊版的

**Comment by hungmi** [comment]
@godorzme ok我再改回來
