### ISSUE TITLE
自己的頁面的「評價」改成「關於我的評價」

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#38]

**Comment by carlos411** [comment]
@godorzme 
請問是以下這個嗎？
我本機url： `http://localhost:3000/profile`
<img width="1215" alt="screen shot 2015-11-24 at 7 50 42 am" src="https://cloud.githubusercontent.com/assets/2485529/11353660/19cf4faa-9280-11e5-9b45-4b1f2a4b4628.png">

若不是，再麻煩提供url及畫面，感謝啊~。

**Comment by godorzme** [comment]
不是這個 但也是這一頁
@hungmi把它隱藏了 請重新顯示

**Comment by carlos411** [comment]
@godorzme @hungmi 
文字部份再麻煩 @hungmi 直接調整即可。感謝~~
