### ISSUE TITLE
左邊目錄的「必填資料」改成「基礎資訊」

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#42]
https://zuker-beta.herokuapp.com/houses/3/basic

**Comment by carlos411** [comment]
@godorzme @hungmi 
<img width="1250" alt="screen shot 2015-11-18 at 1 22 52 pm" src="https://cloud.githubusercontent.com/assets/2485529/11233353/b195d904-8df7-11e5-87a1-ff679b27a07c.png">

updated to master.

抱歉我之後不會更新到master branch，突然想到 @hungmi 有說過更新到master會直接上到server的樣子，之後我會直接合併到 develop 這個 branch。

**Comment by godorzme** [comment]
所以這份現在友存在於develop branch嗎?

**Comment by hungmi** [comment]
現在有
