### ISSUE TITLE
全景下面的小圖的拉霸刪除，做成左右動畫 

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#51]
https://zuker-beta.herokuapp.com/houses/2

如同這樣:http://taiwaning.wix.com/taiwaning#!atlantis-1/cj48
左右隨著滑鼠移動

**Comment by carlos411** [comment]
@godorzme @hungmi 
此issue應該可以 close。 儘量避免做跟滑鼠有關的動態效果。

**Comment by godorzme** [comment]
OK  沒問題  是因為手機介面的關係嗎?
