### ISSUE TITLE
刊登房子直接做一個連結顯示在右上角 

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#6]
能直接點那個連結近刊登房子的頁面

**Comment by carlos411** [comment]
@hungmi 
branch： feature/#6_add_link
url：首頁即可看到(http://localhost:3000/)
view：`app/views/common/_user_nav.html.erb`
```
<li>
  <a href="/houses/new">刊登房子</a>
</li>
```

示意圖：
<img width="1278" alt="screen shot 2015-11-09 at 2 55 29 pm" src="https://cloud.githubusercontent.com/assets/2485529/11027616/33a8d5c0-86f2-11e5-8593-590cb4353494.png">
