### ISSUE TITLE
搜尋時要搜尋整層住家不應該能選房型

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#62]

**Comment by hungmi** [comment]
@carlos411 目前已加入判斷若選擇整層住家，則不顯示房間相關選項，但須重新整理。
因此使用者從整層住家改成分租套雅房時，房間選項依然存在，要等搜尋後才會隱藏，再麻煩你製作相關動作。

**Comment by godorzme** [comment]
![image](https://cloud.githubusercontent.com/assets/15365098/11323344/05782bac-914b-11e5-82c8-dc20fcff491c.png)
目前的搜尋只剩三個  麻煩修復

**Comment by hungmi** [comment]
@godorzme 按照我們目前預設的狀況，一開始能用的就是那三個不是嗎？

**Comment by godorzme** [comment]
疑我們有說過要把它改成只有這三個嗎?
原本的即可  只是在選整層出租的時候  套雅房那欄要不能選擇

**Comment by godorzme** [comment]
沒灌系先這樣好了  房子不多初期影響不大
但麻煩把消失的放在進階搜尋裡
