### ISSUE TITLE
分租套雅房中、房間的安全設施 放在公共

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#67]

**Comment by hungmi** [comment]
@godorzme 你的意思是這樣嗎？
![image](https://cloud.githubusercontent.com/assets/8531846/11324244/203f4684-9167-11e5-8fef-98ee523514a0.png)

**Comment by godorzme** [comment]
放在家俱及設施就可以了
因為之前是看到在每個創造房間都有這個選項才改的
