### ISSUE TITLE
心願單下的房子不應該能編輯，並把刪除功能做成點心號即可

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#7]

**Comment by carlos411** [comment]
@hungmi 

branch： feature/#7_wish_list

此 issue 我看功能面似乎是ok的，我有將幾個haml檔轉成.html.erb。
其中有一行是我無法轉的，如下：
檔案： `app/views/houses/_house.html.erb`
以下這行我註解掉，麻煩協助轉成.html.erb的語法即可。
```
<!--
   %span.house-vote-count{ data: { house_id: house.id } }= house.votes.reload.size
-->
```

**Comment by carlos411** [comment]
@hungmi 
上述我已經更換了。

**Comment by hungmi** [comment]
@godorzme done

**Comment by godorzme** [comment]
愛心的按鈕不見了，無法變成心願

**Comment by hungmi** [comment]
目前狀況為**搜尋結果**以及**房源頁面**中，「**加入心願單的愛心**」在**使用者尚未通過驗證**時不會出現
應改為**預設即出現**，但點擊後**引導使用者進行驗證**
