### ISSUE TITLE
個人資料必須要可以編輯，並加上whatsapp和LINE

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#71]

**Comment by godorzme** [comment]
無法編輯郵件  並把姓名統一(目前是姓和名分開填)

**Comment by hungmi** [comment]
@godorzme 那之後可能會有無法區分姓或名的狀況，ok嗎？

**Comment by godorzme** [comment]
因為我注意到他們自介時  會只顯示名子，但在房東這裡看起來很怪，我們也還沒設計稱謂的系統
還是你有辦法在這部分先讓性與名一起出限?
