### ISSUE TITLE
房源頁面

### ISSUE THREAD

**Issue by carlos411** [godorzme/zuker#73]
#56 房元頁面中顯示的平面照(不論小圖或大圖)都會切到

#15 Google map 的顯示範圍再大一點

**Comment by carlos411** [comment]
@godorzme @hungmi 
branch: `feature/#73_house_source`
我本機端網址： `http://localhost:3000/houses/3`

示意圖：
1、上方的照片區域，還麻煩 @hungmi 協助解決 #56 haml → erb 的問題，我再接續來處理
2、地圖下方我先留著，方便之後後端整合時對照用。
![zuker 2015-11-20 01-11-51](https://cloud.githubusercontent.com/assets/2485529/11277977/e6a14f8e-8f23-11e5-87d9-0fa14479f505.png)

有問題再跟我說，感謝~

**Comment by godorzme** [comment]
讚!再來就試小圖片的對照和資訊的連接，相是我們線在的表格跟上面的不太一樣

**Comment by carlos411** [comment]
@godorzme 
好的喔，我先放上去的原因，是後來想想icon的圖跟文字，可能資料庫要存，所以其實那部份應該可以直接提供給 @hungmi 即可。

後續再跟你討論頁面相關問題喔。感謝~

**Comment by godorzme** [comment]
Ok!

**Comment by godorzme** [comment]
@carlos411  @hungmi 
麻煩先處理照片會切到的問題

**Comment by carlos411** [comment]
@hungmi 可先整合 #73 的頁面，房源頁面的程式似乎用成了你的版本(app/views/houses/show.html.erb，)，若還沒有確定該 feature 整合好，建議不要合併該feature。另外我切換到 #73 似乎也跑不起來了，如下圖：
<img width="1273" alt="screen shot 2015-11-24 at 7 08 57 am" src="https://cloud.githubusercontent.com/assets/2485529/11352911/422f8e34-927a-11e5-9eba-6d1fa24044fc.png">

**Comment by carlos411** [comment]
新的 branch name： `#73_house_source_2`

**Comment by carlos411** [comment]
@hungmi @godorzme 
branch： `feature/#73_house_source_2`
我本機端 url： `http://localhost:3000/houses/431e6028-1206-4bd5-9c23-7ee496eb61cc`
@hungmi 在麻煩整合(假資料部份可任何刪減，style有問題再跟我說，感謝。)。

另外font-awesome，我在此issue，已經安裝好(目前為4.5.0版本)，
我的安裝方式如下：
1、建立 `app/assets/stylesheets/plugins/font-awesome/font-awesome.scss` 檔案
2、建立 `app/assets/` 資料夾，將icon字型檔，都放在此資料夾。
3、在上述第1點的 `font-awesome.scss` 檔案，將路徑指定如下(其中一個範例)：
```
src: asset-url('fontawesome-webfont.eot?v=4.5.0');
```

頁面示意圖：
![zuker 2015-11-25 16-42-58](https://cloud.githubusercontent.com/assets/2485529/11392391/5dc54e5c-9394-11e5-8081-64a74b960d77.png)

**Comment by godorzme** [comment]
@carlos411 能麻煩把傢俱與設施兩個兩個排序嗎?如下:(因為英文的版型會跑掉)參考至airbnb
![image](https://cloud.githubusercontent.com/assets/15365098/11392529/598aba60-9395-11e5-9b70-bc252719945b.png)
到時候需要做一個"隱藏顯示"了，因為會太長
另外空間也要兩個兩個
![image](https://cloud.githubusercontent.com/assets/15365098/11392556/85bdc2ee-9395-11e5-9722-a9f72a751b65.png)

**Comment by carlos411** [comment]
@godorzme @hungmi 
以下再提供2張示意圖。

<img width="1265" alt="screen shot 2015-11-25 at 4 56 50 pm" src="https://cloud.githubusercontent.com/assets/2485529/11392578/a3da7ede-9395-11e5-84a0-26b410c153c8.png">

<img width="1270" alt="screen shot 2015-11-25 at 4 56 55 pm" src="https://cloud.githubusercontent.com/assets/2485529/11392592/b219782e-9395-11e5-8b4e-84b0d0d4126b.png">

@hungmi 
`app/views/partials/_theta_slide.html.erb`
有一行程式(若不是theta的圖的話，要加上not_theta這個class喔，感謝。)：
```
<div class="per_item not_theta">
```

**Comment by carlos411** [comment]
@godorzme 
更新如下：
![zuker 2015-11-25 17-19-15](https://cloud.githubusercontent.com/assets/2485529/11393105/c25d388a-9398-11e5-9974-21e2adc651ac.png)

**Comment by hungmi** [comment]
坪數的地方高度會跑掉
![image](https://cloud.githubusercontent.com/assets/8531846/11414100/3250d5fa-942c-11e5-8cba-b26be7dc41a2.png)

**Comment by hungmi** [comment]
@godorzme 此處性別的翻譯可能要配合圈圈改為Male、Female、Both，可以嗎？
![image](https://cloud.githubusercontent.com/assets/8531846/11414344/4154031c-942f-11e5-92bf-6432800db6d3.png)

**Comment by godorzme** [comment]
可以男 女 不顯示 嗎
