### ISSUE TITLE
在刊登照片時，明明是不同張照片、顯示的時候卻是同張，必須修正

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#74]
https://zuker.herokuapp.com/houses/5/photo

**Comment by hungmi** [comment]
可以解釋清楚一點嗎？因為那是你的帳號創的房子，我沒辦法進去看

**Comment by godorzme** [comment]
當我再上傳照片的時候，他的顯示會是我上傳了很多張一樣的照片，可是我重付整理後　他又會顯示別張
簡單來說就是無法正確顯示所上傳的照片

**Comment by hungmi** [comment]
我目前還沒遇過這問題，可以麻煩你詳細描述你的操作過程嗎？
或是開會時當面討論
