### ISSUE TITLE
把發布套雅房的房間時，目錄上的image移除

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#75]

**Comment by hungmi** [comment]
@godorzme 這個嗎？？
![image](https://cloud.githubusercontent.com/assets/8531846/11316711/323e1f4c-904d-11e5-9e0d-9576352e2390.png)

**Comment by godorzme** [comment]
不是，是下面的＂房間＂，有一個目錄是ｉｍａｇｅ

**Comment by hungmi** [comment]
現在應該沒了吧？
![image](https://cloud.githubusercontent.com/assets/8531846/11323043/4e7b3aa6-9141-11e5-8938-3434816db0c1.png)

**Comment by godorzme** [comment]
沒問題了
不過房源目錄變得很寬，麻煩@carlos
![image](https://cloud.githubusercontent.com/assets/15365098/11323365/9ec0beaa-914b-11e5-94a3-c39f85553d80.png)

**Comment by carlos411** [comment]
看 @hungmi #82 的說明，已經將container加回去，目前應該沒有頁面太寬的問題。
但後續我會再改過來，建議在layout檔內不要加container，否則頁面會被侷限住。

@godorzme
