### ISSUE TITLE
「最近的學校」改成「想出租給哪些學校?」，並可以「新增學校」

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#8]

**Comment by carlos411** [comment]
@godorzme @hungmi 
不好意思，請提供連結？找不到位置在哪裡。

**Comment by godorzme** [comment]
https://zuker.herokuapp.com/houses/new
需要登入才看的到

**Comment by carlos411** [comment]
@hungmi 
branch：feature/#8_change_text
url：http://localhost:3000/houses/new
view： `app/views/houses/partials/_form.html.erb`
```
<div class="form-group">
    <label for="add_other_school">新增其它學校</label>
    <input type="text" class="form-control" id="add_other_school" placeholder="學校名稱">
  </div>
```


示意圖：
<img width="1200" alt="screen shot 2015-11-09 at 3 38 04 pm" src="https://cloud.githubusercontent.com/assets/2485529/11028274/0ded17a0-86f8-11e5-97df-f1bca840d8dc.png">

**Comment by hungmi** [comment]
@godorzme 我覺得現在做新增學校這功能不太恰當，因為目前我們可以服務的區域不多，不可能讓房東自由新增學校；
如果要做的話，我會建議做成一間房屋可以選擇多所學校的模式，可選的學校名單則由我們這邊直接提供所有台北市的高中職以上名單。

**Comment by godorzme** [comment]
沒問題，改用鴻銘的說法
目前先用勾選的好了!才七間，或許相對容易

本來的想法是，先有第一個"想出粗給哪個學校"，而後下面有個新增按鈕(顯示成"+新增學校")，點下去才會有新的拉霸，只能選一個，再點新增學校才能再選，依此類推

**Comment by godorzme** [comment]
以後假設學校多的畫會是先請房東選區域(個個行政區等等)，在由區域內的房子由房東勾選

**Comment by carlos411** [comment]
@hungmi @godorzme 

branch： `feature/#8_change_text`
view： `app/views/houses/partials/_form.html.erb`
url：http://localhost:3000/houses/new

```
<%#= f.association :school, collection: School.categories, prompt: true %>
  <div class="form-group select required house_school">
    <label class="select required control-label" for="house_school_id"><abbr title="必填">*</abbr> 想出租給哪些學校?</label>
    <div class="checkbox">
      <label class="checkbox-inline">
        <input type="checkbox" name="name1" value="1"> 臺灣大學
      </label>
      <label class="checkbox-inline">
        <input type="checkbox" name="name2" value="2"> 政治大學
      </label>
      <label class="checkbox-inline">
        <input type="checkbox" name="name3" value="3"> 世新大學
      </label>
      <label class="checkbox-inline">
        <input type="checkbox" name="name4" value="4"> 台北教育大學
      </label>
      <label class="checkbox-inline">
        <input type="checkbox" name="name5" value="5"> 台灣科技大學
      </label>
      <label class="checkbox-inline">
        <input type="checkbox" name="name6" value="6"> 師範大學
      </label>
      <label class="checkbox-inline">
        <input type="checkbox" name="name7" value="7"> 台北醫護大學
      </label>
    </div>
  </div>
```

示意圖：
<img width="1187" alt="screen shot 2015-11-11 at 11 08 00 am" src="https://cloud.githubusercontent.com/assets/2485529/11082927/8f35ddfc-8864-11e5-9b00-4d51c5684730.png">
