### ISSUE TITLE
當搜尋在複選時，"不限學校"不應該能與其他學校一同複選

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#80]

**Comment by hungmi** [comment]
@godorzme 目前即使使用者複選後，我在伺服器會把它濾掉，因此不會影響搜尋結果，要修改的話需要研究ui本身設定，由於 @carlos411 之後會更換ui，我建議之後一起修正即可。

**Comment by godorzme** [comment]
沒問題
