### ISSUE TITLE
「描述」分解成「房源介紹」與「環境介紹」

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#9]

**Comment by carlos411** [comment]
@godorzme @hungmi 
這想這個應該是這頁：
<img width="879" alt="screen shot 2015-11-09 at 10 53 26 pm" src="https://cloud.githubusercontent.com/assets/2485529/11036637/bf169ff6-8734-11e5-8080-ae249e4b9759.png">

是指最左邊選項一樣描述，然後右邊那些欄位，拆成「房源介紹」與「環境介紹」？
還是最左邊選項"描述"移除，改成有兩個選項「房源介紹」與「環境介紹」？各自的欄位？

**Comment by godorzme** [comment]
把描述刪除，改成房源介紹與環境介紹

**Comment by godorzme** [comment]
房源顯示那邊也要調整成兩個都顯示

**Comment by carlos411** [comment]
那請問「房源介紹」與「環境介紹」各自會哪些欄位呢？
1、名稱、描述、住客規定、適合性別、房屋朝向，這幾個我想應該是房源介紹。
2、環境介紹？

**Comment by godorzme** [comment]
抱歉 我的意思是目錄的描述下的描述改成這兩個 都說敘述性文字

**Comment by carlos411** [comment]
頁面：
```
app/views/houses/profiles/description.html.haml
```

**Comment by carlos411** [comment]
@hungmi 
branch：`feature/#9_description`
view：`app/views/houses/profiles/description.html.erb`
url：`http://localhost:3000/houses/26/description`

更新的code：
```
<%= f.input :description, :input_html => {:rows => 7} %>
    <div class="form-group text optional house_description">
      <label class="text optional control-label" for="house_description">房源介紹</label>
      <textarea rows="7" class="text optional form-control" placeholder="房源介紹" name="house[description]" id="house_description"></textarea>
    </div>
    <div class="form-group text optional house_description">
      <label class="text optional control-label" for="house_description">環境介紹</label>
      <textarea rows="7" class="text optional form-control" placeholder="環境介紹" name="house[description]" id="house_description"></textarea>
    </div>
```

示意圖：
<img width="853" alt="screen shot 2015-11-10 at 6 01 37 pm" src="https://cloud.githubusercontent.com/assets/2485529/11059512/1fc0136e-87d5-11e5-80dc-f8c2503645d9.png">

**Comment by hungmi** [comment]
done

**Comment by godorzme** [comment]
抱歉我現在才注意到，如果是如示意圖，要把"描述"拿掉，剩下兩個介紹即可

**Comment by hungmi** [comment]
@godorzme 
https://zuker-beta.herokuapp.com/houses/1/description
