### ISSUE TITLE
使用者在個人頁面可以瀏覽"我寫下的評價"和"關於我的評價"，並且其他使用者在頁面下面可以留下給他的評論

### ISSUE THREAD

**Issue by godorzme** [godorzme/zuker#93]

**Comment by hungmi** [comment]
![image](https://cloud.githubusercontent.com/assets/8531846/11456791/aa1e6980-96cf-11e5-8639-1b3872e3987f.png)
![image](https://cloud.githubusercontent.com/assets/8531846/11456792/b5df6d1e-96cf-11e5-8416-0ce90fe6a766.png)
